name: "Python-lint-annotate: maintain code quality with annotated PRs and pushes"
description: "Zero-configuration GitHub Action to maintain code quality with push and PR annotations."
branding:
  icon: "alert-triangle"
  color: "yellow"
inputs:
  python3-root-folder:
    description: "The name of the folder that contains python 3 files"
    required: false
    default: "python3"
  use-pylint:
    description: "Use Pylint"
    required: false
    default: true
  use-pycodestyle:
    description: "Use pycodestyle"
    required: false
    default: true
  use-flake8:
    description: "Use Flake8"
    required: false
    default: true
  use-black:
    description: "Use Black"
    required: false
    default: true
  use-mypy:
    description: "Use mypy"
    required: false
    default: true
  use-isort:
    description: "Use isort"
    required: false
    default: true
  use-vulture:
    description: "Use vulture"
    required: false
    default: true
  use-pydocstyle:
    description: "Use pydocstyle"
    required: false
    default: true
  extra-pylint-options:
    description: "Extra options: pylint $(extra-pylint-options) $(python3-root-folder)"
    required: false
    default: ""
  extra-pycodestyle-options:
    description: "Extra options: pycodestyle $(extra-pycodestyle-options) $(python3-root-folder)"
    required: false
    default: ""
  extra-flake8-options:
    description: "Extra options: flake8 $(extra-flake8-options) $(python3-root-folder)"
    required: false
    default: ""
  extra-black-options:
    description: "Extra options: black --check $(extra-black-options) $(python3-root-folder)"
    required: false
    default: ""
  extra-mypy-options:
    description: "Extra options: mypy $(extra-mypy-options) $(python3-root-folder)"
    required: false
    default: ""
  extra-isort-options:
    description: "Extra options: isort -rc $(extra-isort-options) $(python3-root-folder) -c --diff "
    required: false
    default: ""
  extra-vulture-options:
    description: "Extra options: vulture $(extra-vulture-options) $(python3-root-folder)"
    required: false
    default: ""
  extra-pydocstyle-options:
    description: "Extra options: pydocstyle $(extra-pydocstyle-options) $(python3-root-folder)"
    required: false
    default: ""
  conda-python-version:
    description: "Tests are run in Conda environment, set desired python version with this keyword"
    required: false
    default: "3.8"

runs:
  using: "composite"
  steps:
    - name: Install Conda environment from environment.yml
      uses: luceda/provision-with-micromamba@main
      with:
        environment-file: false
        environment-name: lintpy3
        channels: conda-forge
        cache-env: true
        cache-env-key: ${{ inputs.conda-python-version }}
        extra-specs: |
          git
          jq
          curl
          black
          flake8=3.9.1
          isort=5.7.0
          mypy=0.800
          pycodestyle=2.7.0
          pydocstyle=5.1.1
          pylint=2.12
          vulture=2.4
          python=${{ inputs.conda-python-version }}
    - run: >
        ${{ github.action_path }}/entrypoint.sh
        '${{ inputs.python3-root-folder }}'
        ${{ inputs.use-pylint }}
        ${{ inputs.use-pycodestyle }}
        ${{ inputs.use-flake8 }}
        ${{ inputs.use-black }}
        ${{ inputs.use-mypy }}
        ${{ inputs.use-isort }}
        ${{ inputs.use-vulture }}
        ${{ inputs.use-pydocstyle }}
        '${{ inputs.extra-pylint-options }}'
        '${{ inputs.extra-pycodestyle-options }}'
        '${{ inputs.extra-flake8-options }}'
        '${{ inputs.extra-black-options }}'
        '${{ inputs.extra-mypy-options }}'
        '${{ inputs.extra-isort-options }}'
        '${{ inputs.extra-vulture-options }}'
        '${{ inputs.extra-pydocstyle-options }}'
      shell: bash -l {0}
      name: Lint
